# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 23:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortLinks', '0002_auto_20160831_2316'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='links',
            table='Links',
        ),
    ]
