# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortLinks', '0003_auto_20160831_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='links_short_id',
            field=models.SlugField(default=0),
        ),
    ]
