# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortLinks', '0005_auto_20160831_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='links',
            name='links_login',
        ),
    ]
