# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortLinks', '0006_remove_links_links_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='links_login',
            field=models.CharField(default='', max_length=50),
        ),
    ]
