# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortLinks', '0007_links_links_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='links_http',
            field=models.URLField(default='', max_length=255),
        ),
    ]
