# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 20:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortLinks', '0008_auto_20160901_1909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='links',
            old_name='links_short_id',
            new_name='links_short',
        ),
    ]
