# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortLinks', '0012_auto_20160904_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='login',
            field=models.CharField(max_length=50),
        ),
    ]
